version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kanban-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanban_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanban-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/kanban_db?schema=public
      - JWT_SECRET=super-secret-key-123
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: kanban-frontend
    restart: always
    ports:
      # Пробрасываем 80 порт из контейнера на 8080 хоста (чтобы не нужен был sudo)
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: